[WIP] Issue 250
Ptt-official-app/go-pttbbs pull request #251
Opened 2021-08-29 07:18 UTC by tingyuchang

## 這個 PR 的目的 / Purpose of this PR

Update user numLoginDays, LastLogin and LastSeen
But the num increases 1 for every single day from 00:00

## 相關的 issue / Related Issues
#250

2021-08-29 13:03 UTC, chhsiao1981 commented on ptt/mbbsd.go
> +	today := time.Date(time.Now().Year(), time.Now().Month(), time.Now().Day(), 0, 0, 0, 0, time.Now().Location())
這樣子的寫法並不會拿到 today～
你每次都是重新用 time.Now 拿一次～

time.Now 其實是有點花資源～

https://github.com/ptt/pttbbs/blob/master/mbbsd/passwd.c#L525

這也是為啥這裡是只有 baseref 是跟 localtime 有關～
其他都是直接用 unix-timestamp 比較～

2021-08-29 14:09 UTC, tingyuchang commented on ptt/mbbsd.go
> +	today := time.Date(time.Now().Year(), time.Now().Month(), time.Now().Day(), 0, 0, 0, 0, time.Now().Location())
好，我想一下怎麼改～

2021-08-29 17:05 UTC, tingyuchang commented on ptt/mbbsd.go
> +	today := time.Date(time.Now().Year(), time.Now().Month(), time.Now().Day(), 0, 0, 0, 0, time.Now().Location())
@chhsiao1981 
已修改，請再幫忙看看，謝謝

另外有個問題
```
 regdays =      (    reftime - baseref) / DAY_SECONDS;
 prev_regdays = (u.lastlogin - baseref) / DAY_SECONDS;
```
這一段不用無條件進位嗎？

2021-08-29 17:09 UTC, chhsiao1981 requested changes
非常感謝 update!

1. by convention: 請把 pwcuLoginSave 搬到 ptt/passwd.go 裡～
2. 如果可以的話～ 請加上 tests～ (如果不知道怎樣子弄 tests 的話～ 我可以再幫忙 PR 一下～)

    https://github.com/cweill/gotests

3. 有發現到 lint 沒過～
    不知可否在你的 editor 上裝

    https://github.com/mvdan/gofumpt#installation

    這個 package 應該是會自動幫你做 lint 上的修改～

2021-08-29 17:12 UTC, tingyuchang commented
1. ok，沒問題
2. test 我再補，先給你看看這樣的寫法 ok  不 ok 
3. 謝謝，我也覺得我應該要裝一下，每次都是 push 之後才發現問題

2021-08-30 10:37 UTC, tingyuchang commented
@chhsiao1981 測試案例弄好了，有空時請幫忙看看，謝謝～

2021-08-30 14:13 UTC, chhsiao1981 commented on ptt/mbbsd.go
> +	today := time.Date(time.Now().Year(), time.Now().Month(), time.Now().Day(), 0, 0, 0, 0, time.Now().Location())
(都是無條件退位 XD 所以其實沒差 XD)

2021-08-30 14:15 UTC, chhsiao1981 approved these changes
/lgtm

2021-08-30 14:15 UTC, merged